### ISSUE TITLE
LSI ProvisionedThroughput is not existed

### ISSUE THREAD

**Issue by ArronHsiao** [enGMzizo/copy-dynamodb-table#24]
Hi, I found errors in index.js for **table.LocalSecondaryIndexes[i].ProvisionedThroughput** is **undefined**. I modified the following code for LSI and it works :

      if (table.LocalSecondaryIndexes[i].ProvisionedThroughput){
        delete table.LocalSecondaryIndexes[i].ProvisionedThroughput.LastIncreaseDateTime
        delete table.LocalSecondaryIndexes[i].ProvisionedThroughput.LastDecreaseDateTime
        delete table.LocalSecondaryIndexes[i].ProvisionedThroughput.NumberOfDecreasesToday
      }

**Comment by danielrive** [comment]
Hello, i had the same error.
I tested adding comments to the lines and all works fine.
@ArronHsiao  your solution is the more apropiate.

Thanks
