### ISSUE TITLE
Callback function is not called

### ISSUE THREAD

**Issue by LudoPL** [enGMzizo/copy-dynamodb-table#33]
Hi !
I am starting using your great tool.
It seems to work well except my callback function is not called.
I have looked briefly at the code and I wonder if it doesn't come from those lines
```
if (options.source.active && options.destination.active) { // both tables are active
    return startCopying(options, function (err, data) {
      if (err) {
        return fn(err, data)
      }
      if (options.continuousBackups) {
        setContinuousBackups(options, fn)
      }
    })
  }
  ```
  I am in the case where both tables are active and `options.continuousBackups` is false.

**Comment by LudoPL** [comment]
I have push a PR regarding that issue : https://github.com/enGMzizo/copy-dynamodb-table/pull/34
It fix it for me but I haven't look all the code to ensure there is no similar problem elsewhere.

Thanks for you project !

**Comment by enGMzizo** [comment]
fixed in https://github.com/enGMzizo/copy-dynamodb-table/releases/tag/v2.2.0
